[2025-06-10T07:59:26.082+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: news_ingestion_pipeline.filter_existing_articles manual__2025-06-10T07:53:50.735117+00:00 [queued]>
[2025-06-10T07:59:26.089+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: news_ingestion_pipeline.filter_existing_articles manual__2025-06-10T07:53:50.735117+00:00 [queued]>
[2025-06-10T07:59:26.090+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 3
[2025-06-10T07:59:26.110+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): filter_existing_articles> on 2025-06-10 07:53:50.735117+00:00
[2025-06-10T07:59:26.116+0000] {standard_task_runner.py:60} INFO - Started process 78 to run task
[2025-06-10T07:59:26.119+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'news_ingestion_pipeline', 'filter_existing_articles', 'manual__2025-06-10T07:53:50.735117+00:00', '--job-id', '152', '--raw', '--subdir', 'DAGS_FOLDER/rss_scrap_dag.py', '--cfg-path', '/tmp/tmprk2e3zh3']
[2025-06-10T07:59:26.122+0000] {standard_task_runner.py:88} INFO - Job 152: Subtask filter_existing_articles
[2025-06-10T07:59:26.179+0000] {task_command.py:423} INFO - Running <TaskInstance: news_ingestion_pipeline.filter_existing_articles manual__2025-06-10T07:53:50.735117+00:00 [running]> on host 44e96206a18a
[2025-06-10T07:59:26.265+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='news_ingestion_pipeline' AIRFLOW_CTX_TASK_ID='filter_existing_articles' AIRFLOW_CTX_EXECUTION_DATE='2025-06-10T07:53:50.735117+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-10T07:53:50.735117+00:00'
[2025-06-10T07:59:26.986+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/rss_scrap_dag.py", line 53, in step_2_filter_existing
    filtered = filter_existing_articles(articles, project, dataset, table)
  File "/opt/airflow/src/ingestion/rss_filter.py", line 27, in filter_existing_articles
    existing_ids = get_existing_ids_from_bigquery(project_id, dataset_id, table_id, all_ids)
  File "/opt/airflow/src/ingestion/rss_filter.py", line 20, in get_existing_ids_from_bigquery
    return {row.id for row in query_job.result()}
  File "/home/airflow/.local/lib/python3.10/site-packages/google/cloud/bigquery/job/query.py", line 1595, in result
    do_get_result()
  File "/home/airflow/.local/lib/python3.10/site-packages/google/api_core/retry.py", line 372, in retry_wrapped_func
    return retry_target(
  File "/home/airflow/.local/lib/python3.10/site-packages/google/api_core/retry.py", line 207, in retry_target
    result = target()
  File "/home/airflow/.local/lib/python3.10/site-packages/google/cloud/bigquery/job/query.py", line 1584, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.10/site-packages/google/cloud/bigquery/job/base.py", line 971, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/google/api_core/future/polling.py", line 261, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Syntax error: Unexpected ")" at [4:22]; reason: invalidQuery, location: query, message: Syntax error: Unexpected ")" at [4:22]

Location: europe-west1
Job ID: a5e9a38c-353f-48c4-86d3-f8b636a730de

[2025-06-10T07:59:27.001+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=news_ingestion_pipeline, task_id=filter_existing_articles, execution_date=20250610T075350, start_date=20250610T075926, end_date=20250610T075927
[2025-06-10T07:59:27.011+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 152 for task filter_existing_articles (400 Syntax error: Unexpected ")" at [4:22]; reason: invalidQuery, location: query, message: Syntax error: Unexpected ")" at [4:22]

Location: europe-west1
Job ID: a5e9a38c-353f-48c4-86d3-f8b636a730de
; 78)
[2025-06-10T07:59:27.054+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-06-10T07:59:27.076+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
