[2025-06-07T20:34:17.448+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: rss_ingestion_dag.extract_and_load manual__2025-06-07T20:34:16.082934+00:00 [queued]>
[2025-06-07T20:34:17.455+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: rss_ingestion_dag.extract_and_load manual__2025-06-07T20:34:16.082934+00:00 [queued]>
[2025-06-07T20:34:17.455+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-06-07T20:34:17.467+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): extract_and_load> on 2025-06-07 20:34:16.082934+00:00
[2025-06-07T20:34:17.473+0000] {standard_task_runner.py:60} INFO - Started process 75 to run task
[2025-06-07T20:34:17.477+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'rss_ingestion_dag', 'extract_and_load', 'manual__2025-06-07T20:34:16.082934+00:00', '--job-id', '39', '--raw', '--subdir', 'DAGS_FOLDER/rss_ingestion_dag.py', '--cfg-path', '/tmp/tmpcivd8smc']
[2025-06-07T20:34:17.481+0000] {standard_task_runner.py:88} INFO - Job 39: Subtask extract_and_load
[2025-06-07T20:34:17.542+0000] {task_command.py:423} INFO - Running <TaskInstance: rss_ingestion_dag.extract_and_load manual__2025-06-07T20:34:16.082934+00:00 [running]> on host dd2d6a82bb53
[2025-06-07T20:34:17.613+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='rss_ingestion_dag' AIRFLOW_CTX_TASK_ID='extract_and_load' AIRFLOW_CTX_EXECUTION_DATE='2025-06-07T20:34:16.082934+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-07T20:34:16.082934+00:00'
[2025-06-07T20:34:18.639+0000] {rss_ingestion_dag.py:31} INFO - 0 nouveaux articles sur 29 récupérés (doublons ignorés : 29)
[2025-06-07T20:34:18.706+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/rss_ingestion_dag.py", line 35, in extract_and_load
    file_path = upload_to_gcs(articles, bucket_name, prefix)
  File "/opt/airflow/src/utils/gcs_writer.py", line 11, in upload_to_gcs
    timestamp = datetime.datetime.utcnow().strftime("%Y%m%dT%H%M%S")
AttributeError: type object 'datetime.datetime' has no attribute 'datetime'
[2025-06-07T20:34:18.721+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=rss_ingestion_dag, task_id=extract_and_load, execution_date=20250607T203416, start_date=20250607T203417, end_date=20250607T203418
[2025-06-07T20:34:18.731+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 39 for task extract_and_load (type object 'datetime.datetime' has no attribute 'datetime'; 75)
[2025-06-07T20:34:18.775+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-06-07T20:34:18.793+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
