[2025-06-08T16:39:49.114+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: news_ingestion_pipeline.filter_existing_articles manual__2025-06-08T16:39:42.625756+00:00 [queued]>
[2025-06-08T16:39:49.121+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: news_ingestion_pipeline.filter_existing_articles manual__2025-06-08T16:39:42.625756+00:00 [queued]>
[2025-06-08T16:39:49.122+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-06-08T16:39:49.135+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): filter_existing_articles> on 2025-06-08 16:39:42.625756+00:00
[2025-06-08T16:39:49.141+0000] {standard_task_runner.py:60} INFO - Started process 62 to run task
[2025-06-08T16:39:49.145+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'news_ingestion_pipeline', 'filter_existing_articles', 'manual__2025-06-08T16:39:42.625756+00:00', '--job-id', '61', '--raw', '--subdir', 'DAGS_FOLDER/rss_scrap_dag.py', '--cfg-path', '/tmp/tmph80x7kzs']
[2025-06-08T16:39:49.148+0000] {standard_task_runner.py:88} INFO - Job 61: Subtask filter_existing_articles
[2025-06-08T16:39:49.201+0000] {task_command.py:423} INFO - Running <TaskInstance: news_ingestion_pipeline.filter_existing_articles manual__2025-06-08T16:39:42.625756+00:00 [running]> on host 44e96206a18a
[2025-06-08T16:39:49.271+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='news_ingestion_pipeline' AIRFLOW_CTX_TASK_ID='filter_existing_articles' AIRFLOW_CTX_EXECUTION_DATE='2025-06-08T16:39:42.625756+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-08T16:39:42.625756+00:00'
[2025-06-08T16:39:50.450+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/rss_scrap_dag.py", line 46, in step_2_filter_existing
    filtered = [
  File "/opt/airflow/dags/rss_scrap_dag.py", line 48, in <listcomp>
    if a["id"] not in set(
TypeError: unhashable type: 'dict'
[2025-06-08T16:39:50.461+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=news_ingestion_pipeline, task_id=filter_existing_articles, execution_date=20250608T163942, start_date=20250608T163949, end_date=20250608T163950
[2025-06-08T16:39:50.474+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 61 for task filter_existing_articles (unhashable type: 'dict'; 62)
[2025-06-08T16:39:50.522+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-06-08T16:39:50.544+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
