[2025-06-06T16:50:55.816+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: rss_ingestion_dag.extract_and_load manual__2025-06-06T16:50:52.642085+00:00 [queued]>
[2025-06-06T16:50:55.823+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: rss_ingestion_dag.extract_and_load manual__2025-06-06T16:50:52.642085+00:00 [queued]>
[2025-06-06T16:50:55.824+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-06-06T16:50:55.834+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): extract_and_load> on 2025-06-06 16:50:52.642085+00:00
[2025-06-06T16:50:55.840+0000] {standard_task_runner.py:60} INFO - Started process 56 to run task
[2025-06-06T16:50:55.844+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'rss_ingestion_dag', 'extract_and_load', 'manual__2025-06-06T16:50:52.642085+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/rss_ingestion_dag.py', '--cfg-path', '/tmp/tmpmnj85pvr']
[2025-06-06T16:50:55.848+0000] {standard_task_runner.py:88} INFO - Job 5: Subtask extract_and_load
[2025-06-06T16:50:55.907+0000] {task_command.py:423} INFO - Running <TaskInstance: rss_ingestion_dag.extract_and_load manual__2025-06-06T16:50:52.642085+00:00 [running]> on host 702a5a4567ed
[2025-06-06T16:50:55.979+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='rss_ingestion_dag' AIRFLOW_CTX_TASK_ID='extract_and_load' AIRFLOW_CTX_EXECUTION_DATE='2025-06-06T16:50:52.642085+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-06T16:50:52.642085+00:00'
[2025-06-06T16:50:58.215+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/rss_ingestion_dag.py", line 30, in extract_and_load
    logging.info(f"{new} nouveaux articles sur {total} récupérés (doublons ignorés : {total - new})")
NameError: name 'logging' is not defined
[2025-06-06T16:50:58.227+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=rss_ingestion_dag, task_id=extract_and_load, execution_date=20250606T165052, start_date=20250606T165055, end_date=20250606T165058
[2025-06-06T16:50:58.239+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 5 for task extract_and_load (name 'logging' is not defined; 56)
[2025-06-06T16:50:58.267+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-06-06T16:50:58.283+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
