[2025-06-10T08:04:52.404+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: news_ingestion_pipeline.filter_existing_articles manual__2025-06-10T08:04:48.710655+00:00 [queued]>
[2025-06-10T08:04:52.412+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: news_ingestion_pipeline.filter_existing_articles manual__2025-06-10T08:04:48.710655+00:00 [queued]>
[2025-06-10T08:04:52.413+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-06-10T08:04:52.426+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): filter_existing_articles> on 2025-06-10 08:04:48.710655+00:00
[2025-06-10T08:04:52.433+0000] {standard_task_runner.py:60} INFO - Started process 93 to run task
[2025-06-10T08:04:52.437+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'news_ingestion_pipeline', 'filter_existing_articles', 'manual__2025-06-10T08:04:48.710655+00:00', '--job-id', '157', '--raw', '--subdir', 'DAGS_FOLDER/rss_scrap_dag.py', '--cfg-path', '/tmp/tmppa6ow7oq']
[2025-06-10T08:04:52.440+0000] {standard_task_runner.py:88} INFO - Job 157: Subtask filter_existing_articles
[2025-06-10T08:04:52.489+0000] {task_command.py:423} INFO - Running <TaskInstance: news_ingestion_pipeline.filter_existing_articles manual__2025-06-10T08:04:48.710655+00:00 [running]> on host 44e96206a18a
[2025-06-10T08:04:52.556+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='news_ingestion_pipeline' AIRFLOW_CTX_TASK_ID='filter_existing_articles' AIRFLOW_CTX_EXECUTION_DATE='2025-06-10T08:04:48.710655+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-10T08:04:48.710655+00:00'
[2025-06-10T08:04:52.941+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/rss_scrap_dag.py", line 55, in step_2_filter_existing
    filtered_path = upload_to_gcs(filtered, bucket, prefix)
  File "/opt/airflow/src/utils/gcs_writer.py", line 15, in upload_to_gcs
    blob.upload_from_string(json.dumps(data, ensure_ascii=False, indent=2), content_type='application/json')
  File "/usr/local/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/local/lib/python3.10/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/usr/local/lib/python3.10/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/usr/local/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type set is not JSON serializable
[2025-06-10T08:04:52.956+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=news_ingestion_pipeline, task_id=filter_existing_articles, execution_date=20250610T080448, start_date=20250610T080452, end_date=20250610T080452
[2025-06-10T08:04:52.966+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 157 for task filter_existing_articles (Object of type set is not JSON serializable; 93)
[2025-06-10T08:04:53.013+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-06-10T08:04:53.033+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
